spring:
  application:
    name: hexagonal-architecture

  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: asdf1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    ROOT: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  tomcat:
    access-log:
      enabled: true
  port: 8081