# .github/workflows/pr-ci.yml
name: PR Build & Test

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create application-prod.yml from Secrets
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./api/src/main/resources/application-prod.yml

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run tests and build
        run: ./gradlew clean test bootJar

      - name: Comment PR on success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ 빌드 및 테스트가 성공적으로 완료되었습니다!'
            })

      - name: Comment PR on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ 빌드 또는 테스트가 실패했습니다. 로그를 확인해주세요.'
            })
